config/routes.rb
Fsb::Application.routes.draw do
 
  resources :users #, :only => [:new, :edit, :show]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :memberships
  resources :bets, :only => [:new, :create]
  resources :password_resets
  
  match '/signup',                          :to => 'users#new'
  match '/signin',                          :to => 'sessions#new'
  match '/signout',                         :to => 'sessions#destroy'
  match '/join',                            :to => 'memberships#new'
  match '/new_league',                      :to => 'leagues#new'
  match '/rules',                           :to => 'leagues#rules'
  match '/leagues_all',                     :to => 'leagues#index'
	match '/parlay_header',										:to => 'bets#parlay_header'
	match '/add_parlay',											:to => 'bets#new_parlay'
	match '/create_parlay',										:to => 'bets#create_parlay'
	match '/add_to_parlay',										:to => 'bets#add_to_parlay'
  match '/leagues/add_bet',                 :to => 'bets#new'
  match '/leagues/:id/matchups',            :to => 'leagues#matchups'
  match '/bets/submitted',                  :to => 'bets#submitted'
  match '/memberships/:id/unlock_buy_in',   :to => 'memberships#unlock_buy_in'
  match '/memberships/:id/unlock_buy_back', :to => 'memberships#unlock_buy_back'
  match '/memberships/:id/deploy_credits',  :to => 'memberships#deploy_credits'
  match '/super_user',                      :to => 'users#super_user'
  match '/super_user/:id/settings',         :to => 'users#su_settings'
  match '/super_user/:id/users',            :to => 'users#su_users'
  match '/super_user/credit_update',        :to => 'memberships#credit_update'
  
  resources :leagues do
    resources :bets, :only => [:index]
    resources :users, :only => [:index]
    resources :games, :only => [:index]
    member do
      get 'admin'
    end
  end 
  
  root :to => 'sessions#new'
  
end

app/models/admin.rb
require 'digest'
class Admin < ActiveRecord::Base
  has_many :games
  has_many :leagues
  
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
    
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,     :presence     => true,
                       :length       => { :maximum => 50 }
  validates :email,    :presence     => true,
                       :format       => { :with => email_regex },
                       :uniqueness   => { :case_sensitive => false }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
                       
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil   if user.nil?
    return user  if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
end

app/models/league.rb
require 'digest'
require 'ostruct'
class League < ActiveRecord::Base
  has_many :bets, :dependent => :destroy
  has_many :users, :through => :bets
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :matchups, :dependent => :destroy
  has_attached_file :photo,
                    :styles => {:small => "160x120>", :thumb => "50x40"},
                    :storage => :s3,
                    :bucket => ENV['fsb'],
                    :default_url => '/:attachment/:class/missing_:style.png',
                    :s3_credentials => {
                      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                    }
  
  serialize :league_settings, Hash
  serialize  :schedule, OpenStruct
  attr_accessor   :password
  attr_accessible :name, :password, :password_confirmation,
                  :manager, :photo, :league_settings, :start_date, :number_of_weeks
  
  validates :name,            :presence     => true,
                              :uniqueness   => { :case_sensitive => false }
  validates :password,        :presence     => true,
                              :confirmation => true
  validates :number_of_weeks, :numericality => { :greater_than => 0 }
  
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)  
  end
  
  def self.authenticate(league_name, submitted_password)
    league = find_by_name(league_name)
    return nil     if league.nil?
    return league  if league.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    league = find_by_id(id)
    (league && league.salt == cookie_salt) ? league : nil
  end
  
  def set_start_date
    # assumes league manager entered start date so it exists already
    # updates it to be the Tuesday before at 6AM EST.
    temp_start = self.start_date
    
    #convert to EST
    temp_start = temp_start.in_time_zone('America/New_York')
    #set hour to 6AM
    temp_start = temp_start.change(:hour => 6 )
    #roll back a day until day is Tuesday
    until temp_start.tuesday?
      temp_start = temp_start.yesterday
    end
    
    self.start_date = temp_start
    
  end
  
  def schedule_games
    # team number '-1' represents a bye week and should be parsed as such

    # if odd number of teams add 'bye week'
    team_user_ids = []
    self.users.each do |t|
      team_user_ids << t.id
    end
    team_user_ids.sort
    if team_user_ids.length.odd?
      team_user_ids << -1
    end
    
    # figure out what week of the league it is
    weeks_since_start = self.what_week

    # get matchups
    m = self.matchups
    
    # delete matchups for this week forward
    unless m.nil?
      m.each do |m_up|
        if m_up.week >= weeks_since_start
          m_up.delete
        end
      end
    end

    # reset schedule from that week on via round robin algorithm
    for week in weeks_since_start..(self.number_of_weeks)
      
      # replace with new matchups
      for m_up in 1..(team_user_ids.length/2)
        new_matchup = Matchup.new
        new_matchup.league_id       = self.id
        new_matchup.week            = week;
        new_matchup.away_team_id    = team_user_ids[m_up-1]
        new_matchup.home_team_id    = team_user_ids[-m_up]
        new_matchup.away_team_score = 0
        new_matchup.home_team_score = 0
        new_matchup.save
      end
      
      #rotate
      temp_array = team_user_ids[1..-1]
      for index in 0..(temp_array.length-1)
        team_user_ids[index+1] = temp_array[index-1]
      end    
    end  
  end

	# ----------- Adds bye weeks for a new member to the league -#
	# -----------		for weeks in the past -----------------------#
	def add_bye_weeks( m )
		for week in 1..(self.what_week - 1)
        new_matchup = Matchup.new
        new_matchup.league_id       = self.id
        new_matchup.week            = week;
        new_matchup.away_team_id    = -1
        new_matchup.home_team_id    = m.user_id
        new_matchup.save
		end
	end
  
  # -------- returns the given week in a league
  def what_week
    days_since_start = (DateTime.now.utc - self.start_date.to_datetime.utc)
    weeks_since_start = 1
    if days_since_start > 0
      weeks_since_start = (days_since_start.to_f / 7.0).floor + 1 # first week is '1' not '0'
    end

    return weeks_since_start
  end
  
  # ---------- returns a formatted string for matchup page for matchup header
  # takes a week number and user and returns appropriate string
  def matchup_string( user_id, week_number )
    
    if (user_id == -1) || (self.opponent( user_id, week_number ) == -1)
      return "BYE WEEK"
    else
      opponent_user = User.find( self.opponent( user_id, week_number ) )
      opponent_score = self.score( opponent_user.id, week_number )
      user = User.find( user_id )
      user_score = self.score( user_id, week_number )
      if self.home?( user_id, week_number )
        return "#{opponent_user.name} (#{opponent_score})     vs     #{user.name} (#{user_score})"
      else
        return "#{user.name} (#{user_score})     vs     #{opponent_user.name} (#{opponent_score})"
      end  # if for checking home team
    end # if for -1 for bye week
  end
  
  # ---------- returns true if given user on given week is the home team
  def home?( user_id, week_number )
    m = Matchup.where( :league_id    => self.id,
                       :home_team_id => user_id,
                       :week         => week_number).first
    if m.nil?
      return false
    else
      return true
    end
  end
  
  # ---------- returns the id of an opponent given one user id and a week, or -1 if on bye
  def opponent( user_id, week_number )
    m = Matchup.where( :league_id    => self.id,
                       :home_team_id => user_id,
                       :week         => week_number).first
    unless m.nil?
      opponent_id = m.away_team_id
    end
    
    if m.nil?
      m = Matchup.where( :league_id    => self.id,
                         :away_team_id => user_id,
                         :week         => week_number).first
      opponent_id = m.home_team_id
    end
    
    return opponent_id
    
  end
  
  # ------ returns the number of correct lock picks for a user and week ------#
  # ------ only correct if game is final -------------------------------------#
  def score( user_id, week_number )
    # get matchup
    matchup = Matchup.user_matchup( self.id, user_id, week_number )
    # if home team, return home team score
    if matchup.home_team?( user_id )
      return matchup.home_team_score
    else
    # if away team, return away team score
      return matchup.away_team_score
    end
  end
  
  # ------ Updates the League Record at the end of the week ------ #
  # ------ Allocates credits to winner, subtracts from loser ----- #
  def self.update_matchups
    # if it's tuesday... (heroku can't run weekly, so have to do daily)
    if DateTime.now.tuesday?
      puts "**********updating_matchups --> #{Time.now} **************"
      League.all.each do |l|
        # get matchups
        last_week = l.what_week - 1
        matchups = Matchup.league_matchups( l.id, last_week )

        matchups.each do |m|
          Membership.update_credits_for_matchup( m, l.league_settings["h2h_bet"] )
        end
      end # each league
      
    end # if
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_filter :authenticate,   :only => [:new, :create]
  before_filter :league_member,  :only => [:show, :matchups]
  before_filter :league_manager, :only => [:edit, :destroy, :update, :admin]
  before_filter :admin_user,     :only => [:index]
  
  def rules
    
  end
  
  def index
  end
  
  def new
    @league = League.new
    @page_title = "New League"
  end
  
  def create
    @league = League.new(params[:league])
    @league.start_date = @league.set_start_date
    @user = current_user
    @games = Game.open_games
    if @league.save
      join_as_mgr @league, @user
      redirect_to @league
    else
      @page_title = "Sign up"
      render :new
    end
  end
  
  def show
    @page_title = "League Home"
    @league = League.find(params[:id])
    @user = current_user
    @locks = current_user.this_weeks_locks( @league, @user.id, @league.what_week )
    @games = Game.open_games.sort! { |a, b| a.game_time <=> b.game_time }
    @membership = Membership.where(:league_id => @league.id, :user_id => @user.id).first
 
  end
  
  def edit
    @league = League.find(params[:id])
    @page_title = "Edit League"
  end
  
  def update
    @league = League.find(params[:id])
    if @league.update_attributes(params[:league])
      flash[:success] = "League updated."
      redirect_to @league
    else
      @title = "Edit league"
      render 'edit'
    end
  end
  
  def destroy
		League.destroy(params[:id])
		redirect_to '/'
  end
  
  def list_users
    @league = League.find(params[:league])
    
    respond_to do |format|
      format.js
    end
  end
  
  def admin
    @league = League.find(params[:id])
    @users = @league.users
  end
  
  def matchups
    @l = League.find(params[:id])
    @m = @l.matchups

    respond_to do |format|
      format.js {
        @week_number = params[:week_number].to_i
        @user = User.find(params[:user_id])
        @league = @l
    		@matchups = @m
      }
      format.html
    end
  end
  
  private
  
    def authenticate
      deny_access unless signed_in?
    end
    
    def league_member
      not_in_league unless in_league?
    end
    
    def league_manager
      deny_access unless ( manager?(params[:id], current_user.id) || super_user? ) 
    end
    
    def admin_user
      redirect_to(root_path) unless super_user?
    end
  
end

app/helpers/leagues_helper.rb
module LeaguesHelper

end

app/views/leagues/admin.html.erb
<div id="league_info_container" class="round" data-league_id=<%= params[:id] %> >
  
	<%= render 'layouts/league_header', :user => current_user, :league => @league %>

  <div class='round' id='admin_container'> 
    <div>
      <h3><pre class='header'>   User                     Buy-In   Buy-Back   Remove</pre></h3>
    </div>
    <div>  
      <ul>
      <% @users.each do |u| %>
        <li class='no_bullet'>
          <%= render 'layouts/user_admin_view', :user => u, :membership => Membership.where(:league_id => @league.id, :user_id => u.id).first, :league => @league %>
        </li>
      <% end %>  
      </ul>
    </div>
		<div id='edit_delete_container'>
			<%= link_to "Edit Settings", edit_league_path(@league), html_options = {:class => 'button left round'} %>
			<%= button_to "Delete League", league_path, :method => 'delete', :class => 'button right round', :confirm => "Are you sure?" %>
		</div>
  </div>
    
</div>

app/views/leagues/edit.html.erb
<div class="sign_in_container">

  <div class="sign_in_right">
    <h1> Fantasy Sports Book </h1>
    <p> Welcome to Fantasy Sports Book!  Our goal is to
    provide a new and entertaining alternative to your
    standard fantasy sports leagues.  We incorporate the
    best of sports betting and fantasy sports in an addicitve
    and competative format.  Sign up and start your league
    today!</p>
  </div>
  
  <div class="sign_in_left">
    
    <h2 class="sign_in">Update Your League</h2>
  
    <%= form_for @league, :html => { :multipart => true, :class => 'sign_in_form new_league'} do |f| %>
      <%= render 'shared/league_error_messages', :object => f.object %>
      <p>*See "Rules" page for details regarding the settings</p>
      <div class="league_name"><br>
        <div class="field">
          League Name:
          <%= f.text_field :name %>
        </div>
        <div class="field">
            League Password:
            <%= f.password_field :password %>
        </div>
        <div class="field">
            Confirm Password:
            <%= f.password_field :password_confirmation %>
        </div>
      </div>
      <div class="league_members">
        <br>
        Send Invites
      </div>
      <div class="league_settings">
        <br>
        <%= f.fields_for :league_settings do |s| %>
          <p>
            Starting Credits (recommend 10,000):
            <%= s.text_field  :start_credits, :value => @league.league_settings["start_credits"] %>
          </p>
          <p>
            # of Buy Backs (recommend 2):
            <%= s.text_field  :buy_backs,     :value => @league.league_settings["buy_backs"] %>
          </p>
          <p>
            Head 2 Head Bet Amount (recommend 1,000):
            <%= s.text_field  :h2h_bet,       :value => @league.league_settings["h2h_bet"] %>
          </p>
        <% end %>
      </div>
      <div class="field">
          <%= f.label :photo, "Photo" %>
          <%= f.file_field :photo, :size => 5 %>
      </div>
      <div class="actions">
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/leagues/index.html.erb
<div>
  <% for i in 0..(@home_teams.length-1) %>
    <p> <%= "#{@game_ids[i]}" %></p>
    <p> <%= "#{@over_unders[i]}" %></p>
    <p> <%= "#{@spreads[i]}"%></p>
  <% end %>
</div>  

app/views/leagues/league.html.erb
<div>
  <%= games %>
</div>

app/views/leagues/list_users.js.erb
alert("here")

app/views/leagues/matchups.html.erb
<% week_number = @l.what_week %>
<div id="league_info_container" class="round" data-league_id=<%= params[:id] %> data-user_id=<%= current_user.id %> >

	<%=render 'layouts/league_header', :user => current_user, :league => @l %>
  
  <%= render 'layouts/h2h', :week_number => week_number, :user => current_user, :league => @l %>

  <div class='league_container left round'>
    <h2 class='centered underlined no_bottom_margin'>Select a Week</h2>
    <div id='week_list_container'>
      <% for w in 1..(@l.number_of_weeks) %>
        <% if w == week_number %>
          <% sel = "selected" %>
        <% else %>
          <% sel = "" %>
        <% end %>
        <%= render 'layouts/week_button', :week_number => w, :selected =>  sel %>
      <% end %>
    </div>
  </div>

  <%= render 'layouts/weekly_matchups', :week_number => week_number, :user => current_user, :league => @l, :matchups => @m %>

</div>

app/views/leagues/matchups.js.erb
$('#matchup_container').replaceWith("<%= escape_javascript( render 'layouts/h2h', :week_number => @week_number, :user => @user, :league => @league ) %>")

$('#weekly_matchups').replaceWith("<%= escape_javascript( render 'layouts/weekly_matchups', :week_number => @week_number, :user => @user, :league => @league, :matchups => @matchups ) %>" )

jQuery('.matchup').each(function(index,button){
	jQuery(button).click(function(){
		week_number = $('#matchup_container').attr('data-week')
		home_team_id = $(this).attr("data-home_team_id")
		away_team_id = $(this).attr("data-away_team_id")
        user_id = (home_team_id > away_team_id) ? home_team_id : away_team_id
        league_id = $('#league_info_container').attr("data-league_id");
		path_string = '/leagues/' + league_id + '/matchups'
        selector_string = 'week_number=' + week_number + '&user_id=' + user_id
		$.ajax({
			url: path_string,
			type: 'GET',
            data: selector_string
		})
	})
})

app/views/leagues/new.html.erb
<div class="sign_in_container">

  <div class="sign_in_right">
    <h1> Fantasy Sports Book </h1>
    <p> Welcome to Fantasy Sports Book!  Our goal is to
    provide a new and entertaining alternative to your
    standard fantasy sports leagues.  We incorporate the
    best of sports betting and fantasy sports in an addicitve
    and competative format.  Sign up and start your league
    today!</p>
  </div>
  
  <div class="sign_in_left">
    
    <h2 class="sign_in">Create New League</h2>
  
    <%= form_for @league, :html => { :multipart => true, :class => 'sign_in_form new_league'} do |f| %>
      <%= render 'shared/league_error_messages', :object => f.object %>
      <p>*See "Rules" page for details regarding the settings</p>
      <div class="league_name"><br>
        <div class="field">
          League Name:
          <%= f.text_field :name %>
        </div>
        <div class="field">
            League Password:
            <%= f.password_field :password %>
        </div>
        <div class="field">
            Confirm Password:
            <%= f.password_field :password_confirmation %>
        </div>
        <div class='field'>
          Start Date:            
          <%= f.date_select :start_date %>
        </div>
        <div class='field'>
          Number of Weeks:
          <%= f.text_field :number_of_weeks %>
        </div>
      </div>
      <div class="league_members">
        <br>
        Send Invites
      </div>
      <div class="league_settings">
        <br>
        <%= f.fields_for :league_settings do |s| %>
          <p>
            Starting Credits (recommend 10,000):
            <%= s.text_field  :start_credits, :value => @league.league_settings["start_credits"] %>
          </p>
          <p>
            # of Buy Backs (recommend 2):
            <%= s.text_field  :buy_backs,     :value => @league.league_settings["buy_backs"] %>
          </p>
          <p>
            Head 2 Head Bet Amount (recommend 1,000):
            <%= s.text_field  :h2h_bet,       :value => @league.league_settings["h2h_bet"] %>
          </p>
        <% end %>
      </div>
      <div class="field">
          <%= f.label :photo, "Photo" %>
          <%= f.file_field :photo, :size => 5 %>
      </div>
      <div class="actions">
        <br>
        <%= f.submit "Sign up" %>
      </div>
    <% end %>
  </div>
</div>


app/views/leagues/show.html.erb
<div id="league_info_container" class="round" data-league_id=<%= params[:id] %> data-user_id=<%= current_user.id %> data-membership_id=<%= @membership.id %> >
	<%=render 'layouts/league_header', :user => @user, :league => @league %>
  
  <div class="profile_container round">
    <div class="header">
      <h2>Profile - <%= @user.name %></h2>
    </div>
    <%= render 'layouts/profile', :user => @user, :membership => @membership, :league => @league %>
  </div>
  
  <div class="bets_container round">
    <div class="header">
      <h2>Games</h2>
    </div>
    <div class="content">
      <% @games.each do |game| %>
        <%= render 'layouts/bets', :game => game %> 
      <% end %>
    </div>
  </div>
  
  <div id="locks_container" class="round">
    <div class="header">
      <h2>Head 2 Head Locks</h2>
    </div>
    <div id="locks">
      <%= render 'layouts/locks', :locks => @locks %>
    </div>
  </div>
  
  <div id="bet_slip_container" class="round">
    <div class="header">
      <h2>Bet Slip</h2>
    </div>
    <div class="content">

    </div>
    <div class="footer">
      <p class="footer_container left">
        Total Risk: <span id="total_risk">0</span>
      </p>
      <p class="footer_container right">
        To Win: <span id="total_win">0</span>
      </p>
    </div>
    <div class="footer footer2">    
			<%= submit_tag "Place Bets", :class => "button right" %>
      <%= submit_tag "Clear Bets", :class => "button right"%>
    </div>
  </div>

  
  <div id="league_standings_container" class="round">
    <div class="header">
      <h2>League Standings</h2>
    </div>
    <div class="content">
      <%= render 'layouts/league_standings', :league => @league %>
    </div>
  </div>

</div>